language: node_js
node_js: 10.15.3

sudo: false

#cache
cache:
  directories:
    - "node_modules"

notifications:
  # 钉钉机器人消息推送部署结果
  webhooks:
    urls:
      - https://oapi.dingtalk.com/robot/send?access_token=0201af34ab411cca7eedd47dce7d0370601b9fa0d17b294916c57504edab4a2c
    on_success: always 
    on_failure: always 
    
  # 邮件发送部署结果通知
  email:
    recipients:
      - mumushum@163.com
    on_success: never
    on_failure: always

# S: Build Lifecycle
install:
  - npm install
#  - gem install travis
#  - travis login --pro --github-token ${GH_TOKEN}

before_script:
  - export TZ='Asia/Shanghai'
  - npm install --save-dev gulp-notify@3.0.0
  - npm install -g gulp
  - chmod +x _travis.sh

script:
  - hexo clean && hexo g
  # 复制谷歌搜索凭证到该目录
  - cp ./License/googleb47a830154cebabf.html ./public/
  # excute gulp
  - gulp
  
after_success:
 # - LAST_BUILD_NUMBER=68
 # - for i in $(seq 1 $LAST_BUILD_NUMBER ); do  travis logs $i --delete --force ; done

after_script:
  - ./_travis.sh

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/Syngnath/Syngnath.github.io.git